export const semesterData = [
    {
        semester: 1,
        papers: [
            {
                name: "PROGRAMMING FOR PROBLEM SOLVING THROUGH C BCAC101",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-1-sem-programming-for-problem-solving-bcac-101-2023.pdf",
            },
            {
                name: "DIGITAL ELECTRONICS BCAC102",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-1-sem-digital-electronics-bcac-102-2023.pdf",
            },
            {
                name: "PROGRAMMING FOR PROBLEM SOLVING THROUGH C BCAC101",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-1-sem-programming-for-problem-solving-bcac-101-2023.pdf",
            },
            {
                name: "DIGITAL ELECTRONICS BCAC102",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-1-sem-digital-electronics-bcac-102-2023.pdf",
            },
            {
                name: "PROGRAMMING FOR PROBLEM SOLVING THROUGH C BCAC101",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-1-sem-c-programming-bcan-103-2020.pdf",
            },
            {
                name: "DIGITAL ELECTRONICS BCAC102",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-1-sem-digital-electronics-bcan-101-2020.pdf",
            },
            {
                name: "PROGRAMMING FOR PROBLEM SOLVING THROUGH C BCAC101",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC101_2020.pdf",
            },
            {
                name: "DIGITAL ELECTRONICS BCAC102",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC102_2020.pdf",
            },
            {
                name: "PROGRAMMING FOR PROBLEM SOLVING THROUGH C BCAC101",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC101_2019.pdf",
            },
            {
                name: "DIGITAL ELECTRONICS BCAC102",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC102_2019.pdf",
            },
            {
                name: "PROGRAMMING FOR PROBLEM SOLVING THROUGH C BCAC101",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC101_2018.pdf",
            },
            {
                name: "DIGITAL ELECTRONICS BCAC102",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC102_2018.pdf",
            },
            {
                name: "PROGRAMMING FOR PROBLEM SOLVING THROUGH C BCAC101",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC101_2017.pdf",
            },
            {
                name: "DIGITAL ELECTRONICS BCAC102",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC102_2017.pdf",
            },
            {
                name: "PROGRAMMING FOR PROBLEM SOLVING THROUGH C BCAC101",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC101_2016.pdf",
            },
            {
                name: "DIGITAL ELECTRONICS BCAC102",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC102_2016.pdf",
            },
            {
                name: "PROGRAMMING FOR PROBLEM SOLVING THROUGH C BCAC101",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC101_2015.pdf",
            },
            {
                name: "DIGITAL ELECTRONICS BCAC102",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC102_2015.pdf",
            },
        ],
    },
    {
        semester: 2,
        papers: [
            {
                name: "DISCRETE MATHEMATICS BCAC201",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-2-sem-discrete-structures-bcac201-2023.pdf",
            },
            {
                name: "DATA STRUCTURES BCAC202",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-2-sem-data-structure-with-c-bcan-203n-2019.pdf",
            },
            {
                name: "DISCRETE MATHEMATICS BCAC201",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-2-sem-discrete-structures-bcac201-2023.pdf",
            },
            {
                name: "DATA STRUCTURES BCAC202",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://www.makaut.com/papers/bca-2-sem-data-structure-with-c-bcan-203n-2019.pdf",
            },
            {
                name: "DISCRETE MATHEMATICS BCAC201",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC201_2021.pdf",
            },
            {
                name: "DATA STRUCTURES BCAC202",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC202_2021.pdf",
            },
            {
                name: "DISCRETE MATHEMATICS BCAC201",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC201_2020.pdf",
            },
            {
                name: "DATA STRUCTURES BCAC202",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC202_2020.pdf",
            },
            {
                name: "DISCRETE MATHEMATICS BCAC201",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC201_2019.pdf",
            },
            {
                name: "DATA STRUCTURES BCAC202",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC202_2019.pdf",
            },
            {
                name: "DISCRETE MATHEMATICS BCAC201",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC201_2018.pdf",
            },
            {
                name: "DATA STRUCTURES BCAC202",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC202_2018.pdf",
            },
            {
                name: "DISCRETE MATHEMATICS BCAC201",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC201_2017.pdf",
            },
            {
                name: "DATA STRUCTURES BCAC202",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC202_2017.pdf",
            },
            {
                name: "DISCRETE MATHEMATICS BCAC201",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC201_2016.pdf",
            },
            {
                name: "DATA STRUCTURES BCAC202",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC202_2016.pdf",
            },
            {
                name: "DISCRETE MATHEMATICS BCAC201",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC201_2015.pdf",
            },
            {
                name: "DATA STRUCTURES BCAC202",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC202_2015.pdf",
            },
        ],
    },
    {
        semester: 3,
        papers: [
            {
                name: "OPERATING SYSTEM BCAC301",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC301_2023.pdf",
            },
            {
                name: "COMPUTER ORGANIZATION BCAC302",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC302_2023.pdf",
            },
            {
                name: "OPERATING SYSTEM BCAC301",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC301_2022.pdf",
            },
            {
                name: "COMPUTER ORGANIZATION BCAC302",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC302_2022.pdf",
            },
            {
                name: "OPERATING SYSTEM BCAC301",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC301_2021.pdf",
            },
            {
                name: "COMPUTER ORGANIZATION BCAC302",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC302_2021.pdf",
            },
            {
                name: "OPERATING SYSTEM BCAC301",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC301_2020.pdf",
            },
            {
                name: "COMPUTER ORGANIZATION BCAC302",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC302_2020.pdf",
            },
            {
                name: "OPERATING SYSTEM BCAC301",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC301_2019.pdf",
            },
            {
                name: "COMPUTER ORGANIZATION BCAC302",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC302_2019.pdf",
            },
            {
                name: "OPERATING SYSTEM BCAC301",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC301_2018.pdf",
            },
            {
                name: "COMPUTER ORGANIZATION BCAC302",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC302_2018.pdf",
            },
            {
                name: "OPERATING SYSTEM BCAC301",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC301_2017.pdf",
            },
            {
                name: "COMPUTER ORGANIZATION BCAC302",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC302_2017.pdf",
            },
            {
                name: "OPERATING SYSTEM BCAC301",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC301_2016.pdf",
            },
            {
                name: "COMPUTER ORGANIZATION BCAC302",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC302_2016.pdf",
            },
            {
                name: "OPERATING SYSTEM BCAC301",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC301_2015.pdf",
            },
            {
                name: "COMPUTER ORGANIZATION BCAC302",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC302_2015.pdf",
            },
        ],
    },
    {
        semester: 4,
        papers: [
            {
                name: "DATABASE MANAGEMENT SYSTEM BCAC401",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC401_2023.pdf",
            },
            {
                name: "OBJECT ORIENTED PROGRAMMING BCAC402",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC402_2023.pdf",
            },
            {
                name: "DATABASE MANAGEMENT SYSTEM BCAC401",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC401_2022.pdf",
            },
            {
                name: "OBJECT ORIENTED PROGRAMMING BCAC402",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC402_2022.pdf",
            },
            {
                name: "DATABASE MANAGEMENT SYSTEM BCAC401",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC401_2021.pdf",
            },
            {
                name: "OBJECT ORIENTED PROGRAMMING BCAC402",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC402_2021.pdf",
            },
            {
                name: "DATABASE MANAGEMENT SYSTEM BCAC401",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC401_2020.pdf",
            },
            {
                name: "OBJECT ORIENTED PROGRAMMING BCAC402",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC402_2020.pdf",
            },
            {
                name: "DATABASE MANAGEMENT SYSTEM BCAC401",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC401_2019.pdf",
            },
            {
                name: "OBJECT ORIENTED PROGRAMMING BCAC402",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC402_2019.pdf",
            },
            {
                name: "DATABASE MANAGEMENT SYSTEM BCAC401",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC401_2018.pdf",
            },
            {
                name: "OBJECT ORIENTED PROGRAMMING BCAC402",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC402_2018.pdf",
            },
            {
                name: "DATABASE MANAGEMENT SYSTEM BCAC401",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC401_2017.pdf",
            },
            {
                name: "OBJECT ORIENTED PROGRAMMING BCAC402",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC402_2017.pdf",
            },
            {
                name: "DATABASE MANAGEMENT SYSTEM BCAC401",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC401_2016.pdf",
            },
            {
                name: "OBJECT ORIENTED PROGRAMMING BCAC402",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC402_2016.pdf",
            },
            {
                name: "DATABASE MANAGEMENT SYSTEM BCAC401",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC401_2015.pdf",
            },
            {
                name: "OBJECT ORIENTED PROGRAMMING BCAC402",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC402_2015.pdf",
            },
        ],
    },
    {
        semester: 5,
        papers: [
            {
                name: "COMPUTER NETWORKS BCAC501",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC501_2023.pdf",
            },
            {
                name: "SOFTWARE ENGINEERING BCAC502",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC502_2023.pdf",
            },
            {
                name: "COMPUTER NETWORKS BCAC501",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC501_2022.pdf",
            },
            {
                name: "SOFTWARE ENGINEERING BCAC502",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC502_2022.pdf",
            },
            {
                name: "COMPUTER NETWORKS BCAC501",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC501_2021.pdf",
            },
            {
                name: "SOFTWARE ENGINEERING BCAC502",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC502_2021.pdf",
            },
            {
                name: "COMPUTER NETWORKS BCAC501",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC501_2020.pdf",
            },
            {
                name: "SOFTWARE ENGINEERING BCAC502",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC502_2020.pdf",
            },
            {
                name: "COMPUTER NETWORKS BCAC501",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC501_2019.pdf",
            },
            {
                name: "SOFTWARE ENGINEERING BCAC502",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC502_2019.pdf",
            },
            {
                name: "COMPUTER NETWORKS BCAC501",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC501_2018.pdf",
            },
            {
                name: "SOFTWARE ENGINEERING BCAC502",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC502_2018.pdf",
            },
            {
                name: "COMPUTER NETWORKS BCAC501",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC501_2017.pdf",
            },
            {
                name: "SOFTWARE ENGINEERING BCAC502",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC502_2017.pdf",
            },
            {
                name: "COMPUTER NETWORKS BCAC501",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC501_2016.pdf",
            },
            {
                name: "SOFTWARE ENGINEERING BCAC502",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC502_2016.pdf",
            },
            {
                name: "COMPUTER NETWORKS BCAC501",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC501_2015.pdf",
            },
            {
                name: "SOFTWARE ENGINEERING BCAC502",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC502_2015.pdf",
            },
        ],
    },
    {
        semester: 6,
        papers: [
            {
                name: "INTERNET TECHNOLOGIES BCAC601",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC601_2023.pdf",
            },
            {
                name: "ARTIFICIAL INTELLIGENCE BCAC602",
                year: 2023,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC602_2023.pdf",
            },
            {
                name: "INTERNET TECHNOLOGIES BCAC601",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC601_2022.pdf",
            },
            {
                name: "ARTIFICIAL INTELLIGENCE BCAC602",
                year: 2022,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC602_2022.pdf",
            },
            {
                name: "INTERNET TECHNOLOGIES BCAC601",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC601_2021.pdf",
            },
            {
                name: "ARTIFICIAL INTELLIGENCE BCAC602",
                year: 2021,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC602_2021.pdf",
            },
            {
                name: "INTERNET TECHNOLOGIES BCAC601",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC601_2020.pdf",
            },
            {
                name: "ARTIFICIAL INTELLIGENCE BCAC602",
                year: 2020,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC602_2020.pdf",
            },
            {
                name: "INTERNET TECHNOLOGIES BCAC601",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC601_2019.pdf",
            },
            {
                name: "ARTIFICIAL INTELLIGENCE BCAC602",
                year: 2019,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC602_2019.pdf",
            },
            {
                name: "INTERNET TECHNOLOGIES BCAC601",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC601_2018.pdf",
            },
            {
                name: "ARTIFICIAL INTELLIGENCE BCAC602",
                year: 2018,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC602_2018.pdf",
            },
            {
                name: "INTERNET TECHNOLOGIES BCAC601",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC601_2017.pdf",
            },
            {
                name: "ARTIFICIAL INTELLIGENCE BCAC602",
                year: 2017,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC602_2017.pdf",
            },
            {
                name: "INTERNET TECHNOLOGIES BCAC601",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC601_2016.pdf",
            },
            {
                name: "ARTIFICIAL INTELLIGENCE BCAC602",
                year: 2016,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC602_2016.pdf",
            },
            {
                name: "INTERNET TECHNOLOGIES BCAC601",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC601_2015.pdf",
            },
            {
                name: "ARTIFICIAL INTELLIGENCE BCAC602",
                year: 2015,
                downloads: 0,
                views: 0,
                link: "https://makaut1.ucanapply.com/smartexam/public/uploads/questionpapers/BCAC602_2015.pdf",
            },
        ],
    },
]

